root: true
env:
  browser: true,
  es2022: true
ignorePatterns:
  - '*.test.js'
extends:
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  prettier/prettier: error
